#include "langstrings.h"

static const LangStrings s_sv = {
  "Sparade sajter...",
  "Anslut",
  "Koppla från",
  "Ansluter...",
  "Stoppa",
  "Host:",
  "Användarnamn:",
  "Lösenord:",
  "Ansluten",
  "Frånkopplad",
  "Lokal sökväg...",
  "Serversökväg...",
  "Status log...",
  "Namn",
  "Storlek",
  "Datum",
  "English",
  "Uppdatera",
  "Skapa mapp",
  "Skapa ny mapp",
  "Byt namn",
  "Ladda upp mapp till server",
  "Ladda upp fil till server",
  "Ta bort",
  "Ta bort mapp",
  "Ladda ner fil",
  "Ladda ner mapp",
  "Ta bort fil",
  "Ansluter till %1:21...",
  "FTP-lösenord",
  "Ange FTP-lösenord:",
  "Anslutningsfel",
  "Ej ansluten",
  "Anslut till servern för att ladda upp.",
  "Anslut till servern för att ladda upp mappar.",
  "Ta bort fil",
  "Är du säker på att du vill ta bort filen '%1'?",
  "Ta bort mapp",
  "Är du säker på att du vill ta bort mappen '%1'?",
  "mapp",
  "fil",
  "mappen",
  "filen",
  "Ta bort %1",
  "Är du säker på att du vill ta bort %1 '%2'?",
  "Ta bort markerade",
  "Är du säker på att du vill ta bort %1 markerade objekt?",
  "Fel",
  "Kunde inte ta bort %1: %2",
  "Kunde inte skapa mappen.",
  "Kunde inte byta namn på objektet.",
  "Skapa mapp",
  "Mappnamn:",
  "Filen finns redan",
  "En fil eller mapp med det namnet finns redan.",
  "Filen finns redan",
  "Filen '%1' finns redan. Skriv över?",
  "Fel",
  "Filen finns inte.",
  "Avsluta",
  "Kopiering av filer pågår. Vill du verkligen avsluta?",
  "Tog bort %1: %2",
};

static const LangStrings s_en = {
  "Saved sites...",
  "Connect",
  "Disconnect",
  "Connecting...",
  "Stop",
  "Host:",
  "Username:",
  "Password:",
  "Connected",
  "Disconnected",
  "Local path...",
  "Server path...",
  "Status log...",
  "Name",
  "Size",
  "Date",
  "Español",
  "Refresh",
  "Create folder",
  "Create new folder",
  "Rename",
  "Upload folder to server",
  "Upload file to server",
  "Delete",
  "Delete folder",
  "Download file",
  "Download folder",
  "Delete file",
  "Connecting to %1:21...",
  "FTP Password",
  "Enter FTP password:",
  "Connection Error",
  "Not connected",
  "Connect to the server to upload.",
  "Connect to the server to upload folders.",
  "Delete file",
  "Are you sure you want to delete the file '%1'?",
  "Delete folder",
  "Are you sure you want to delete the folder '%1'?",
  "folder",
  "file",
  "the folder",
  "the file",
  "Delete %1",
  "Are you sure you want to delete %1 '%2'?",
  "Delete selected",
  "Are you sure you want to delete %1 selected items?",
  "Error",
  "Could not delete %1: %2",
  "Could not create the folder.",
  "Could not rename the item.",
  "Create folder",
  "Folder name:",
  "File already exists",
  "A file or folder with that name already exists.",
  "File exists",
  "File '%1' already exists. Overwrite?",
  "Error",
  "File does not exist.",
  "Quit",
  "File transfer in progress. Do you really want to quit?",
  "Deleted %1: %2",
};

static const LangStrings s_es = {
  "Sitios guardados...",
  "Conectar",
  "Desconectar",
  "Conectando...",
  "Detener",
  "Host:",
  "Usuario:",
  "Contraseña:",
  "Conectado",
  "Desconectado",
  "Ruta local...",
  "Ruta del servidor...",
  "Registro de estado...",
  "Nombre",
  "Tamaño",
  "Fecha",
  "Svenska",
  "Actualizar",
  "Crear carpeta",
  "Crear nueva carpeta",
  "Renombrar",
  "Subir carpeta al servidor",
  "Subir archivo al servidor",
  "Eliminar",
  "Eliminar carpeta",
  "Descargar archivo",
  "Descargar carpeta",
  "Eliminar archivo",
  "Conectando a %1:21...",
  "Contraseña FTP",
  "Introduce la contraseña FTP:",
  "Error de conexión",
  "No conectado",
  "Conéctate al servidor para subir.",
  "Conéctate al servidor para subir carpetas.",
  "Eliminar archivo",
  "¿Estás seguro de que quieres eliminar el archivo '%1'?",
  "Eliminar carpeta",
  "¿Estás seguro de que quieres eliminar la carpeta '%1'?",
  "carpeta",
  "archivo",
  "la carpeta",
  "el archivo",
  "Eliminar %1",
  "¿Estás seguro de que quieres eliminar %1 '%2'?",
  "Eliminar seleccionados",
  "¿Estás seguro de que quieres eliminar %1 elementos seleccionados?",
  "Error",
  "No se pudo eliminar %1: %2",
  "No se pudo crear la carpeta.",
  "No se pudo renombrar el elemento.",
  "Crear carpeta",
  "Nombre de carpeta:",
  "El archivo ya existe",
  "Ya existe un archivo o carpeta con ese nombre.",
  "Archivo existente",
  "El archivo '%1' ya existe. ¿Sobrescribir?",
  "Error",
  "El archivo no existe.",
  "Salir",
  "Transferencia de archivos en curso. ¿Realmente deseas salir?",
  "Eliminado %1: %2",
};

static const LangStrings s_ja = {
  "保存済みサイト...",
  "接続",
  "切断",
  "接続中...",
  "停止",
  "ホスト:",
  "ユーザー名:",
  "パスワード:",
  "接続済み",
  "未接続",
  "ローカルパス...",
  "サーバーパス...",
  "ステータスログ...",
  "名前",
  "サイズ",
  "日付",
  "",
  "更新",
  "フォルダを作成",
  "新しいフォルダを作成",
  "名前の変更",
  "フォルダをサーバーにアップロード",
  "ファイルをサーバーにアップロード",
  "削除",
  "フォルダを削除",
  "ファイルをダウンロード",
  "フォルダをダウンロード",
  "ファイルを削除",
  "%1:21 に接続中...",
  "FTPパスワード",
  "FTPパスワードを入力:",
  "接続エラー",
  "未接続",
  "アップロードするにはサーバーに接続してください。",
  "フォルダをアップロードするにはサーバーに接続してください。",
  "ファイルを削除",
  "ファイル '%1' を削除してもよろしいですか?",
  "フォルダを削除",
  "フォルダ '%1' を削除してもよろしいですか?",
  "フォルダ",
  "ファイル",
  "フォルダ",
  "ファイル",
  "%1を削除",
  "%1 '%2' を削除してもよろしいですか?",
  "選択項目を削除",
  "選択された%1個のアイテムを削除してもよろしいですか?",
  "エラー",
  "%1を削除できませんでした: %2",
  "フォルダを作成できませんでした。",
  "名前を変更できませんでした。",
  "フォルダを作成",
  "フォルダ名:",
  "ファイルが既に存在します",
  "同じ名前のファイルまたはフォルダが既に存在します。",
  "ファイルが存在します",
  "ファイル '%1' は既に存在します。上書きしますか?",
  "エラー",
  "ファイルが存在しません。",
  "終了",
  "ファイルのコピーが進行中です。本当に終了しますか?",
  "%1を削除しました: %2",
};

const LangStrings *s_langs[kNumLangs] = {&s_sv, &s_en, &s_es, &s_ja};
